services:
  php:
    image: php:8.3-fpm
    build: .
    container_name: php
    volumes:
      - .:/var/www/html:cached
      - ./php.ini:/usr/local/etc/php/php.ini
    environment:
      - SYMFONY_ENV=dev
    ports:
      - "9000:9000"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: solitrack
      MYSQL_USER: solitrack
      MYSQL_PASSWORD: "solitrack"
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mariadb
      PMA_USER: solitrack
      PMA_PASSWORD: solitrack
    ports:
      - "8081:80"
    depends_on:
      - mariadb

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

volumes:
  db_data:
