services:
  php:
    image: php:8.3-fpm
    build: .
    container_name: php_solitrack
    volumes:
      - .:/var/www/html:cached
      - ./php.ini:/usr/local/etc/php/php.ini
    environment:
      - SYMFONY_ENV=dev
    ports:
      - "9000:9000"
    depends_on:
      - db_solitrack

  nginx:
    image: nginx:latest
    container_name: solitrack-app_testinstall
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db_solitrack:
    image: mariadb:11.8.2
    container_name: db_solitrack
    environment:
       MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
       MYSQL_DATABASE: ${DB_NAME}
       MYSQL_USER: ${DB_USER}
       MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_USER: ${DB_USER}      
      PMA_PASSWORD: ${DB_PASSWORD}  
    ports:
      - "8081:80"
    depends_on:
      - db_solitrack

volumes:
  db_data:
