name: Build

on: [workflow_call]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP with Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, intl, pdo, pdo_mysql
          tools: composer

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader --no-scripts

      - name: Debug current directory and files
        run: |
          echo "Current directory:"
          pwd
          echo "Contents:"
          ls -la

      - name: Debug content of ./public
        run: |
          if [ -d public ]; then
            echo "Public directory exists, contents:"
            ls -la public
          else
            echo "No public directory found"
          fi

      - name: Prepare build directory
        run: |
          mkdir -p build
          rsync -a --exclude='.git' --exclude='tests' ./ build/


            - name: Upload build artifact
              uses: actions/upload-artifact@v4
              with:
                name: build
                path: build
