name: Build

on: [workflow_call]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP with Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, intl, pdo, pdo_mysql
          tools: composer

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader --no-scripts

      - name: Debug root directory
        run: |
          echo "Current directory:"
          pwd
          echo "Root directory contents:"
          ls -la

      - name: Prepare build directory
        run: |
          mkdir -p build
          rsync -a --exclude='.git' --exclude='tests' --exclude='build' --exclude='var/cache' --exclude='var/log' ./ build/
          echo "Build directory contents after rsync:"
          ls -la build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
