name: Build

on: [workflow_call]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP with Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, intl, pdo, pdo_mysql
          tools: composer

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Compile assets with AssetMapper
        run: php bin/console asset-map:compile

      - name: Prepare build directory
        run: |
          mkdir -p build
          cp -r public/* build/

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
