name: Deploy to o2switch

on:
  push:
    branches: [ci-cd-setup]

jobs:
  test-whitelist:
    runs-on: ubuntu-latest
    steps:
    - name: Get public IP
  id: ip
  uses: haythem/public-ip@v1.3

- name: Clean old whitelist entries and add new IP
  run: |
    curl -sX GET "https://${{ secrets.CPANEL_USERNAME }}:${{ secrets.CPANEL_PASSWORD }}@${{ secrets.CPANEL_SERVER }}:2083/frontend/o2switch/o2switch-ssh-whitelist/index.live.php" | \
    fgrep 'index.live.php?r=remove&address=' | cut -d '"' -f 2 | while read ipToRemove; do
      curl -sX GET "https://${{ secrets.CPANEL_USERNAME }}:${{ secrets.CPANEL_PASSWORD }}@${{ secrets.CPANEL_SERVER }}:2083/frontend/o2switch/o2switch-ssh-whitelist/$ipToRemove" > /dev/null 2>&1
    done

    curl -X POST \
      -d 'whitelist[address]=${{ steps.ip.outputs.ipv4 }}' \
      -d 'whitelist[port]=22' \
      "https://${{ secrets.CPANEL_USERNAME }}:${{ secrets.CPANEL_PASSWORD }}@${{ secrets.CPANEL_SERVER }}:2083/frontend/o2switch/o2switch-ssh-whitelist/index.live.php?r=add" > /dev/null 2>&1

    curl -sX GET "https://${{ secrets.CPANEL_USERNAME }}:${{ secrets.CPANEL_PASSWORD }}@${{ secrets.CPANEL_SERVER }}:2083/frontend/o2switch/o2switch-ssh-whitelist/index.live.php" | fgrep -q "${{ steps.ip.outputs.ipv4 }}" && echo "IP whitelisted"

    sleep 65
