name: Deploy to o2switch

on:
  push:
    branches: [ci-cd-setup]

jobs:
  whitelist-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get the public IP of the GitHub runner
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Debug IP
        run: echo "Runner IP:${{ steps.ip.outputs.ipv4 }}"

      - name: List all whitelisted IPs
        id: list-ips
        run: |
          # Récupérer la liste complète des adresses IP
          JSON_OUTPUT=$(curl -sX GET "https://${{ secrets.CPANEL_USERNAME }}:${{ secrets.CPANEL_PASSWORD }}@${{ secrets.CPANEL_SERVER }}:2083/frontend/o2switch/o2switch-ssh-whitelist/index.live.php?r=list")
          echo "$JSON_OUTPUT" | jq .

          # Extraire les adresses IP et les stocker dans une variable
            IPS=$(echo "$JSON_OUTPUT" | jq -r '.data.list[].address' | sort -u | paste -sd "," -)
            echo "ips=$IPS" >> $GITHUB_OUTPUT

      - name: Remove all whitelisted IPs
        run: |
          # Supprimer chaque adresse IP
          IFS=',' read -ra IP_ARRAY <<< "${{ steps.list-ips.outputs.ips }}"
          for ip in "${IP_ARRAY[@]}"; do
            echo "Removing IP: $ip"
            curl -sX GET "https://${{ secrets.CPANEL_USERNAME }}:${{ secrets.CPANEL_PASSWORD }}@${{ secrets.CPANEL_SERVER }}:2083/frontend/o2switch/o2switch-ssh-whitelist/index.live.php?r=remove&address=$ip&direction=in&port=22"
            curl -sX GET "https://${{ secrets.CPANEL_USERNAME }}:${{ secrets.CPANEL_PASSWORD }}@${{ secrets.CPANEL_SERVER }}:2083/frontend/o2switch/o2switch-ssh-whitelist/index.live.php?r=remove&address=$ip&direction=out&port=22"
          done

      - name: Add runner IP to whitelist
        run: |
          curl -sX POST \
            -d "whitelist[address]=${{ steps.ip.outputs.ipv4 }}" \
            -d "whitelist[port]=22" \
            "https://${{ secrets.CPANEL_USERNAME }}:${{ secrets.CPANEL_PASSWORD }}@${{ secrets.CPANEL_SERVER }}:2083/frontend/o2switch/o2switch-ssh-whitelist/index.live.php?r=add"

      - name: Verify whitelist contains runner IP
        run: |
          curl -sX GET \
            "https://${{ secrets.CPANEL_USERNAME }}:${{ secrets.CPANEL_PASSWORD }}@${{ secrets.CPANEL_SERVER }}:2083/frontend/o2switch/o2switch-ssh-whitelist/index.live.php?r=list" \
            | grep "${{ steps.ip.outputs.ipv4 }}"
