name: Deploy to o2switch

on:
  push:
    branches: [ci-cd-setup]

jobs:
  test-whitelist:
    runs-on: ubuntu-latest
    steps:
      - name: Get the public IP of the GitHub runner
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Debug IP
        run: echo "Runner IP:${{ steps.ip.outputs.ipv4 }}"

      - name: Add the IP to cPanel SSH whitelist
        run: |
          curl -sX POST \
            -d "whitelist[address=${{ steps.ip.outputs.ip }}]" \
            -d "whitelist[port]=22" \
            "https://${{ secrets.CPANEL_USERNAME }}:${{ secrets.CPANEL_PASSWORD }}@${{ secrets.CPANEL_SERVER }}:2083/frontend/o2switch/o2switch-ssh-whitelist/index.live.php?r=add" \
            | jq

      - name: Check the current whitelist
        run: |
          curl -sX GET \
            "https://${{ secrets.CPANEL_USERNAME }}:${{ secrets.CPANEL_PASSWORD }}@${{ secrets.CPANEL_SERVER }}:2083/frontend/o2switch/o2switch-ssh-whitelist/index.live.php?r=list" \
            | jq
