name: Test deploy o2switch

on:
  push:
    branches: [ci-cd-setup]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Test connexion SSH to o2switch
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: dev.solitrack.fr
          username: ${{ secrets.CPANEL_USERNAME }}
          key: ${{ secrets.O2SWITCH_SSH_KEY }}
          script: |
            echo "Connection successful!"
