name: Deploy to o2switch

on:
  push:
    branches: [ci-cd-setup]

jobs:
  whitelist-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get the public IP of the GitHub runner
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Debug IP
        run: echo "Runner IP: ${{ steps.ip.outputs.ipv4 }}"

      - name: Remove all whitelisted IPs
        run: |
          curl -sX GET "https://${{ secrets.CPANEL_USERNAME }}:${{ secrets.CPANEL_PASSWORD }}@${{ secrets.CPANEL_SERVER }}:2083/frontend/o2switch/o2switch-ssh-whitelist/index.live.php" \
          | fgrep 'index.live.php?r=remove&address=' \
          | cut -d '"' -f 2 \
          | while read ipToRemove; do
              curl -sX GET "https://${{ secrets.CPANEL_USERNAME }}:${{ secrets.CPANEL_PASSWORD }}@${{ secrets.CPANEL_SERVER }}:2083/frontend/o2switch/o2switch-ssh-whitelist/$ipToRemove" > /dev/null 2>&1
            done

      - name: Add runner IP to whitelist
        run: |
          curl -sX POST \
            -d "whitelist[address]=${{ steps.ip.outputs.ipv4 }}" \
            -d "whitelist[port]=22" \
            "https://${{ secrets.CPANEL_USERNAME }}:${{ secrets.CPANEL_PASSWORD }}@${{ secrets.CPANEL_SERVER }}:2083/frontend/o2switch/o2switch-ssh-whitelist/index.live.php?r=add"

      - name: Verify whitelist contains runner IP
        run: |
          curl -sX GET \
            "https://${{ secrets.CPANEL_USERNAME }}:${{ secrets.CPANEL_PASSWORD }}@${{ secrets.CPANEL_SERVER }}:2083/frontend/o2switch/o2switch-ssh-whitelist/index.live.php?r=list" \
            | grep "${{ steps.ip.outputs.ipv4 }}"
