name: Deploy to o2switch

on:
  push:
    branches: [ci-cd-setup]

jobs:
  test-whitelist:
    runs-on: ubuntu-latest
    steps:
      - name: Test cPanel login auth (whitelist list)
        run: |
          curl -sX GET "https://${{ secrets.CPANEL_USERNAME}}:${{ secrets.CPANEL_PASSWORD }}@${{ secrets.CPANEL_SERVER }}:2083/frontend/o2switch/o2switch-ssh-whitelist/index.live.php?r=list" | jq
