name: Build and Deploy

on:
  push:
    branches: [ci-cd-setup]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get public IP of the GitHub runner
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Remove all whitelisted IPs (in and out)
        run: |
          curl -sX GET "https://${{ secrets.REMOTE_USER }}:${{ secrets.URL_ENCODED_PASSWORD }}@${{ secrets.REMOTE_HOST }}:2083/frontend/o2switch/o2switch-ssh-whitelist/index.live.php" \
          | fgrep 'index.live.php?r=remove&address=' \
          | cut -d '"' -f 2 \
          | while read ipToRemove; do
              curl -sX GET "https://${{ secrets.REMOTE_USER }}:${{ secrets.URL_ENCODED_PASSWORD }}@${{ secrets.REMOTE_HOST }}:2083/frontend/o2switch/o2switch-ssh-whitelist/$ipToRemove" > /dev/null 2>&1
            done

      - name: Add current runner IP to whitelist on port 22
        run: |
          curl -sX POST \
            -d "whitelist[address]=${{ steps.ip.outputs.ipv4 }}" \
            -d "whitelist[port]=22" \
            "https://${{ secrets.REMOTE_USER }}:${{ secrets.URL_ENCODED_PASSWORD }}@${{ secrets.REMOTE_HOST }}:2083/frontend/o2switch/o2switch-ssh-whitelist/index.live.php?r=add"

      - name: Check that IP is whitelisted
        run: |
          curl -sX GET "https://${{ secrets.REMOTE_USER }}:${{ secrets.URL_ENCODED_PASSWORD }}@${{ secrets.REMOTE_HOST }}:2083/frontend/o2switch/o2switch-ssh-whitelist/index.live.php" \
          | grep "${{ steps.ip.outputs.ipv4 }}" && echo "IP whitelisted"
