name: Deploy to o2switch

on:
  push:
    branches: [ci-cd-setup]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH agent with private key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Test SSH connection
        run: ssh -o StrictHostKeyChecking=no xuzo1696@mortadelle.o2switch.net "echo 'Connexion SSH réussie !'
